version: '3.8'

volumes:
    postgres_data:

services:
    db:
        image: postgres:12.4
        container_name: postgres_db_container
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file:
          - ./.env


    web:
        build: .
        restart: always
        ports:
          - "8000:8000"
        depends_on:
            - db
