"""Create rss feed cache table

Revision ID: d8dfeab54852
Revises: 
Create Date: 2021-03-24 20:12:57.183244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'd8dfeab54852'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rss_feed_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('snapshot', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('news_news')
    op.drop_table('news')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pubdate', sa.VARCHAR(), nullable=True),
    sa.Column('news_items', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_news',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pubdate', sa.VARCHAR(), nullable=True),
    sa.Column('news_items', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('rss_feed_cache')
    # ### end Alembic commands ###
